spring.application.name=
spring.mail.host=
spring.mail.port=
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=
spring.mail.properties.mail.smtp.starttls.enable=

nordic.username=
email.user=

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.jpa.properties.hibernate.dialect=

#Migration with flyway
spring.flyway.enabled=
spring.flyway.baseline-on-migrate=
spring.flyway.user=
spring.flyway.password=
spring.flyway.baseline-description=
spring.flyway.baseline-version=
BREVO_API_KEY=
