spring.application.name=NordicCargoBackend
spring.mail.host=smtp.domeneshop.no
spring.mail.port=587
spring.mail.username=cargo@nordicict.com
spring.mail.password=cargo@NordicIct2
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


email.user="cargo@nordicict.com"
