CREATE TABLE info_model
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sender_email VARCHAR(255)                             NOT NULL,
    sender_name  VARCHAR(255)                             NOT NULL,
    message      VARCHAR(255)                             NOT NULL,
    subject      VARCHAR(255),
    CONSTRAINT pk_info_model PRIMARY KEY (id)
);